### ISSUE TITLE
Eddystone-URL parsing bug with URL expansion

### ISSUE THREAD

**Issue by Aeyoun** [justinodwyer/Beacon-Scanner-and-Logger#5] opened 2015-10-08 20:19 UTC
Hi, there is a problem iwth the URL expansion in your Eddystone-URL implementation. All other scanning apps including Google’s own parse the following broadcast correctly as “`http://www.example.com/`”, but your app interprets it as “`http://www.example.com/.gov/.eduOrlin.com/`”. (Where “Orlin” is the device name, no other Eddystone-URL client display this data anywhere.)

    $ python3.4 advertise-url -v "http://www.example.com/"
    Advertising: http://www.example.com/
    Encoded uri length: 9
    Message: 16 02 01 1a 03 03 aa fe 0e 16 aa fe 10 ed 00 65 78 61 6d 70 6c 65 00 00 00 00 00 00 00 00 00 00
    sudo hciconfig hci0 up
    sudo hcitool -i hci0 cmd 0x08 0x000a 00
    sudo hcitool -i hci0 cmd 0x08 0x0008 16 02 01 1a 03 03 aa fe 0e 16 aa fe 10 ed 00 65 78 61 6d 70 6c 65 00 00 00 00 00 00 00 00 00 00
    sudo hcitool -i hci0 cmd 0x08 0x000a 01

[advertise-url](https://github.com/google/eddystone/blob/master/eddystone-url/implementations/linux-url-advertiser/advertise-url) is Google’s own URL broadcaster for Linux. I provided the raw broadcast above so you don’t really need to run it.

Other tested implementations include Google Chrome for iOS, Opera Mobile Labs for Android, and a bunch of “beacon scanner apps” for Android.

**Comment by justinodwyer** [comment] 2015-10-09 11:21
Interesting. I'm using the AltBeacon iBeacon Library from Radius Networks, and just passing through the value returned as far as I'm aware. I'll crack this open and take a look at it, thanks for taking the time to report this.

**Comment by Aeyoun** [comment] 2015-10-09 12:36
The problem is made invisible with longer URLs. The shorter the URL, the more garbage is added at the end. Possible memory allocation problem/string length?

**Comment by justinodwyer** [comment] 2015-11-13 14:38
OK, finally found time to look into this properly, turns out it was due to this issue here: https://github.com/AltBeacon/android-beacon-library/issues/272 (basically the BeaconParser needs to be configured to correctly manage a variable length URL and the API documentation did not previously reflect this.  

Will build and release a new version, fix has been uploaded to GitHub repository.

Just out of interest, I'd be really interested to know if this was the cause of the 2 start rating you gave the app in Google Play? Are there any changes that if made would cause you to re-evaluate and increase the rating you'd give the app?

All the best,
Justin

**Comment by Aeyoun** [comment] 2015-11-13 14:56
The app didn’t work and, so I gave it a low rating. The app also doesn’t set the standard 16dp padding from screen edges on the main interface (only applied on the toolbar), and doesn’t have an app icon. Those are the main points I remember.

PS: For the icon, you can upload a pure black icon shape to [this tool](https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html) and have it generate quality icons with correct shadowing and shapes for you.

**Comment by justinodwyer** [comment] 2015-11-13 15:04
Thanks for the tips, I'll take a look at those and incorporate them - the icon definitely needs sorting out, it's just not been a priority as of yet.. I get the Eddystone-URL issue, as I was able to recreate it, but the app should "work" so this is a worry.

The new version is in beta, I'll thoroughly test it over the weekend and promote it to live when it's ready.

Thanks again for the feedback, if you're ever tempted to try the app again in future I hope you have a more positive experience. :)

**Comment by justinodwyer** [comment] 2015-11-13 16:35
Fixed version (also featuring icon graphics ;) ) promoted to live, closing issue.

**Closed by justinodwyer** 2015-11-13 16:35 UTC
